### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [GerTorres/Trabajo-final-BioinfRepro-2017-2#1]
Ok, pero recuenda que aunque sean unos pocos loci deberás hacer tus análisis lo más posible utilizando línea de comando y R.

**Comment by AzaleaGuerra** [comment]
Mismo comentario que Alicia. Recuerda que la idea es que apliquen lo que hemos visto en el curso.

**Comment by GerTorres** [comment]
OK, buscaré más información para saber qué de todo el proceso puedo hacerlo en linea de comando y principalmente en R 
@AliciaMstt @AzaleaGuerra 

P.D. De la tarea 4 mi usuario es "Veronica" porque Verito me presto su lap para la clase. Sin embargo, todo lo he hecho en "nuevo", lo único que no tuve que instalar fue Docker, R studio y R.

**Comment by AliciaMstt** [comment]
Ok, eso explica mucho. Si te califiqué con menos esa tarea mándame un correo con el clasmarker y lo corrijo,
