### ISSUE TITLE
comentarios avances3

### ISSUE THREAD

**Issue by AliciaMstt** [GerTorres/Trabajo-final-BioinfRepro-2017-2#3]
Googlea lo de ggtree si no lo has hecho ya, encontré un par de foros que discutían problemas en ubuntu.

Si el script script_commandLine.sh ya contiene las instrucciones de MUSCLE, RaxML, etc, no es necesario que vuelvas a poner los comandos en el readme.

**Comment by GerTorres** [comment]
Busqué el problema y una de las soluciones que daban tampoco me funcionó. Cansado, desistí y ya lo terminé de editar con phytools, ape y geiger. 
Referente al README, al principio tenía las instrucciones en el script pero lo ví muy amontonado y solo le deje los comentarios de que hace en cada paso. ¿Debo volver a comentarlo en el script en lugar del README?

**Comment by GerTorres** [comment]
Así me quedó el árbolito: [Tree](https://github.com/GerTorres/Trabajo-final-BioinfRepro-2017-2/blob/master/Rplot01.pdf) @AliciaMstt
